### ISSUE TITLE
Runno mistakenly handles stdin as though it was shell commands

### ISSUE THREAD

**Issue by katharosada** [taybenlor/runno#178]
When the terminal is waiting for stdin input e.g in Python `input()` the terminal UI waits for a valid-looking shell input and doesn't process the input until quotes are matched and there are no trailing pipes etc.

## Steps to reproduce

1. Create a python program using `input()` and run it.
2. Enter a quote mark into a python `input` prompt, then hit enter.

**Expected behaviour:** Input finishes and Python execution continues

**Actual behaviour:** Prompt continues to wait until the end quote or the input otherwise matches a valid shell command.
The remaining characters (and additional newlines) are added to the stdin buffer and are automatically consumed on the next `input()` call. Causing the next `input` prompt to be skipped over.

Example Python input:
```py
name = input("prompt>> ")
print(f'You entered: {name}')
name = input("prompt>> ")
print(f'You entered: {name}')
```

Example interaction:
```
prompt>> That's nice
> '
You entered: That's nice
prompt>> You entered: '
```

![image](https://user-images.githubusercontent.com/4311392/148721112-231086ba-90bb-48e3-a4c4-15fd602e162b.png)

### Cause

The `isIncompleteInput` check is invoked on enter, regardless of whether the UI is awaiting a bash command or stdin input.

Relevant logic is here:
https://github.com/taybenlor/runno/blob/60b1903913f095521b058cb1ce238915a2c0c5e0/packages/terminal/src/wasm-shell/wasm-shell.ts#L427

**Comment by taybenlor** [comment]
Thanks! That whole `isIncompleteInput` logic should be safe to remove since Runno doesn't use any of `wasm-shell`'s shell-like behaviour. If you're interested I'd love a PR, otherwise I'll investigate myself when I have some free time!
