### ISSUE TITLE
Process EOF (Ctrl D) in Web Terminal

### ISSUE THREAD

**Issue by LukePrior** [taybenlor/runno#190]
I've encountered an issue with detecting EOF (Ctrl D) as the web terminal doesn't seem to register this as a normal terminal would.

DEMO: [here](https://runno.run/?editor=1&runtime=clang&code=I2luY2x1ZGUgPHN0ZGlvLmg-CgojZGVmaW5lIE1BWF9TSVpFIDEwMQoKaW50IG1haW4odm9pZCkgewoKICAgIGludCBudW1iZXJzW01BWF9TSVpFXTsKCiAgICBwcmludGYoIkVudGVyIG51bWJlcnM6IFxuIik7CgogICAgaW50IGkgPSAwOwogICAgd2hpbGUgKHNjYW5mKCIlZCIsICZudW1iZXJzW2ldKSAhPSBFT0YpIHsKICAgICAgICBpKys7CiAgICB9CgogICAgaW50IHkgPSAwOwogICAgd2hpbGUgKHkgPCBpKSB7CiAgICAgICAgcHJpbnRmKCIlZFxuIiwgbnVtYmVyc1t5XSk7CiAgICAgICAgeSsrOwogICAgfQoKICAgIHJldHVybiAwOwp9)

**Suggested Solution**

Implement a handler specifically for `Ctrl + D` and end the interactive capture of STDIN.

**Comment by taybenlor** [comment]
Thanks heaps for filing!

**Comment by taybenlor** [comment]
EOF is now sent over STDIN when `Ctrl + D` is pressed.
