### ISSUE TITLE
Headless Running Pass fs Between Steps

### ISSUE THREAD

**Issue by LukePrior** [taybenlor/runno#191]
The `fs` should be passed during steps when HeadlessRunning.

See https://github.com/taybenlor/runno/discussions/188#discussioncomment-2519773

**Comment by taybenlor** [comment]
Thanks heaps!

**Comment by LukePrior** [comment]
I tried the workaround you suggested but couldn't get that to work so I will just wait for this. Thanks again for the amazing tool.

**Comment by taybenlor** [comment]
This should work in `v0.4.0` with the new `@runno/wasi` implementation.
