### ISSUE TITLE
Support linter in code editor?

### ISSUE THREAD

**Issue by LukePrior** [taybenlor/runno#192]
Hey,

I was looking at the documentation for CodeMirror and saw that it [included](https://codemirror.net/doc/manual.html#addon_lint) native linter support.

A demo can be found [here](https://codemirror.net/demo/lint.html).

I think you would only be able to add support for JavaScript currently but hopefully more are developed.

**Comment by taybenlor** [comment]
I would say this is outside the scope of Runno. It's a really good idea and would be useful in a teaching context, but would be a lot of work that is tangential to the main aim of the project.

Instead what I'd suggest is using Runno without `editor` and then hooking up the `runno-run` element to your own CodeMirror instance. So you use your own editor, and then when students click run it runs inside Runno.

**Comment by LukePrior** [comment]
Good idea Thanks.
