### ISSUE TITLE
Investigate adding support for Nim ( and reactors )

### ISSUE THREAD

**Issue by pmp-p** [taybenlor/runno#217]
i left you a note on discord about that. I had success to build wasi app with wasm-sdk-19 + Nim but i'm having trouble to find a wasi web runner that would offer support for reactors in order to set a standard for using https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame as it should

---

References:
- https://github.com/WebAssembly/wasi-libc/pull/74
- https://github.com/WebAssembly/WASI/issues/13

**Comment by taybenlor** [comment]
Thanks Paul! I've responded in discord. This looks very doable. Is there a description somewhere of how to call a WASI binary that uses reactors? I can see that you start by calling `_initialize` and then you're meant to call a main loop function, but what is that called?

It looks like I might have to read more about the Component model and how it composes collections of imports/exports.

**Comment by amesgen** [comment]
> I can see that you start by calling `_initialize` and then you're meant to call a main loop function, but what is that called?

There is no specific main loop function afterwards, the intention is that the user will then call specific WASM exports as necessary, see https://github.com/WebAssembly/WASI/blob/main/legacy/application-abi.md.

For comparison, see https://github.com/bjorn3/browser_wasi_shim/pull/17 for how another browser WASI shim implements support for WASI reactors.

For `@runno/wasi`, one can currently do this via
```javascript
wasi.instance = instance;
wasi.memory = instance.exports.memory;
instance.exports._initialize();
```
but one could also add a helper function (similar to `wasi.start`) for this as in https://github.com/bjorn3/browser_wasi_shim/pull/17, but it might make sense to wait until the component model/`wasi_snapshot_preview2` is ready.

**Comment by taybenlor** [comment]
Thanks @amesgen! This looks pretty simple to do. I've been trying to follow the NodeJS API (https://nodejs.org/api/wasi.html). I'll have a look at implementing it that way.
