### ISSUE TITLE
Error in runtime "TypeError: import object field 'env' is not an Object"

### ISSUE THREAD

**Issue by booleanchile** [taybenlor/runno#220]
Hi!

I've been trying to run the examples folders with Vite, and it just works with quickjs, but with python and ruby I got the following:

Error in runtime "TypeError: import object field 'env' is not an Object"

I have added the windows.process hack, but the error remains.
Also crossOriginIsolated is set to True.

Please help

**Comment by taybenlor** [comment]
Hi!

Thanks for raising an issue! I've also noticed this error started happening and I'm not sure why. Nothing has changed AFAIK, so it may be a change in the way one of the third party dependencies is working.

I'll look into this on the weekend when I have some time.

You could also check if it works on an older commit against main - maybe I broke something incidentally.

**Comment by booleanchile** [comment]
Hello, thanks for your quick reply.

I checked @runno/runtime and @runno/hot  at 0.2.0, with no luck.  The bad news is that is also happening on production in both chrome and Firefox.

![image](https://user-images.githubusercontent.com/46203382/228578006-eb92d7fa-1fd1-40ae-bbc1-00794bf92a1d.png)

The error message is in both: "python: can't open file 'program': [Errno 44] No such file or directory"
In production quickjs, C and C++ are working.

How can I help?

**Comment by taybenlor** [comment]
Sorry for the radio silence here. I've done a big refactor in https://github.com/taybenlor/runno/pull/221. It looks like https://runno.dev/ is working again. I need to do another release (probably `0.4.0`).

**Comment by taybenlor** [comment]
Hello again, I've got the examples working again in https://github.com/taybenlor/runno/pull/230. Sorry it took so long!
