### ISSUE TITLE
I still hope to support inserting iframes in markdown files as before.

### ISSUE THREAD

**Issue by Sandural** [taybenlor/runno#254]
I can no longer insert iframes into markdown files as before.

**Comment by taybenlor** [comment]
Hi Sandural,

I've decided to deprecate the iframe usage of Runno to focus on the NPM packages.

iframes pointing to `runno.run` should still work, and you can generate a new URL with `@runno/host` and the `generateEmbedURL` function. See: https://github.com/taybenlor/runno/blob/9b9dc1f3142cf883fd37842f73f51bfe7d837ded/packages/host/src/index.ts#L5C17-L5C33

I can't guarantee that these URLs will work long term.

Thanks!
Ben
