### ISSUE TITLE
runno-run tag fetches relative wasm src from /, and not from the local dir

### ISSUE THREAD

**Issue by larsr** [taybenlor/runno#265]
I have a web page in a sub-folder `/debug` on the web server, and its `debug/index.html` has a `<runno-wasi src="./my.wasm">` tag and  a file `/debug/my.wasm`.  

[Problem] But `runno` tries to fetch the file `/my.wasm`, and not `/debug/my.wasm` as was expected.

A work-around is to put the full path in the tag, `<runno-wasi src="/debug/my.wasm">`  , but that is of course undesirable if one wants to move it around later.

**Comment by taybenlor** [comment]
I think it's just doing a `fetch` on the src, so not sure why this isn't working. Might be that `fetch` doesn't handle this particular behaviour.

**Comment by larsr** [comment]
If it doesnt happen to you, it may have been my webproxy/caddy rules that rewrite the url in a confusing way, so I'm closing this for now, and look into it on my side.
