### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by dmarcos** [taybenlor/runno#270]
Just wanted to say thank you. Thanks to the runtime I was able to build [karpathys llama2.c](https://github.com/karpathy/llama2.c) to WASM and [run inference in the browser](https://github.com/dmarcos/llama2.c-web). I have a couple of minor changes locally hacked together that I might contribute: Ability to pass JS functions to the WebAssembly context and also WebAssembly.Memory externally defined.

**Comment by taybenlor** [comment]
Hey! Awesome stuff! Definitely happy to see some contributions. Passing those extra options makes total sense for customisation!
