### ISSUE TITLE
How do you install a package in the python runtime 

### ISSUE THREAD

**Issue by 0x0645** [taybenlor/runno#294]
I want to install some packages in the Python runtime environment for example `NumPy`

**Comment by taybenlor** [comment]
Hi!

The best way to add packages is with the `fs-url`, you can see a demo in the [Examples](https://github.com/taybenlor/runno/tree/main/examples).

```
<h3>Including Files</h3>
        <p>
          You can install files into the filesystem with the <code>fs-url</code>
          attribute. The URL should be a <code>.tar.gz</code> file that includes
          the files you want. This is useful for including packages that can
          then be imported and run as part of the example.
        </p>

        <runno-run runtime="python" fs-url="/python-package.tar.gz" controls editor>
          from package import say_hello
          say_hello()
        </runno-run>
```

However I'm not sure something like `NumPy` would work, as I believe it is reliant on compiled binaries for the target architecture.

If you're interested in a full data-science stack in Python in the browser, I would recommend looking at [Pyodide](https://pyodide.org/en/stable/).

In future could you post this sort of question in the Discussions page, thanks!

**Comment by 0x0645** [comment]
@taybenlor I am so sorry I didn't use the Discussions page. I tried running the examples earlier and it was not working I was getting this exception 

```
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  @runno/runtime (imported by /home/gomaa/Desktop/examples/src/index.ts)

Are they installed?
    at optimizeDeps (/home/gomaa/Desktop/examples/node_modules/vite/dist/node/chunks/dep-3daf770c.js:63749:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOptimize (/home/gomaa/Desktop/examples/node_modules/vite/dist/node/chunks/dep-3daf770c.js:67764:48)
    at async httpServer.listen (/home/gomaa/Desktop/examples/node_modules/vite/dist/node/chunks/dep-3daf770c.js:67780:21)

```
