### ISSUE TITLE
[Question] any option to communicate between wasm and js?

### ISSUE THREAD

**Issue by namse** [taybenlor/runno#296]
Is there a way to communicate between JS and WASM? I know stdio is supported, but that doesn't seem sufficient. I'm wondering if you have any methods in mind, such as loopback sockets or shared memory.

**Comment by taybenlor** [comment]
Hi!

That's not really within the scope of what Runno does. Runno focuses on implementing a runtime compatible with WASI Preview 1. You might be a bit confused about how WASI and Wasm work?

WASM binaries can export any functions they like, so if you wanted to additionally have your own functions you could!

If you'd like to ask further questions I'm happy to answer in the Discussions tab - or you could check out the [Web Assembly discord](https://webassembly.org/community/resources/).
